# Generated by devforge. Do not edit.
# Edit the specs under inst/params/ and run devforge::forge_params().

# parameter checkers -----------------------------------------------------------

#' Check plot params
#'
#' @description Checkmate extension for the output of [params_plots()].
#'
#' @param x The object to check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkPlotParams <- function(x) {
  res <- check_list_shape(
    x,
    c(
      "width",
      "height",
      "file_type",
      "unit",
      "res",
      "create_dir"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      width = "N1",
      height = "N1",
      res = "I1",
      create_dir = "B1"
    ),
    label = "plot params",
    hint = "width, height need to be numericals and res an integer."
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_choice_rules(
    x,
    list(
      file_type = c(".png", ".pdf"),
      unit = c("in", "px", "cm")
    ),
    label = "plot params",
    hint = "width, height need to be numericals and res an integer."
  )
  if (!isTRUE(res)) {
    return(res)
  }

  return(TRUE)
}

#' Assert plot params
#'
#' @inheritParams checkPlotParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertPlotParams <- checkmate::makeAssertionFunction(checkPlotParams)

#' Check volcano params
#'
#' @description Checkmate extension for the output of [params_volcano()].
#'
#' @param x The object to check.
#' @param dt Extra context for the check.
#'
#' @returns `TRUE` if the check was successful, otherwise a
#' checkmate-style error string.
#'
#' @keywords internal
checkVolcanoParams <- function(x, dt = NULL) {
  res <- check_list_shape(
    x,
    c(
      "x_axis",
      "y_axis",
      "colour",
      "label_column",
      "top_features_to_label"
    )
  )
  if (!isTRUE(res)) {
    return(res)
  }

  res <- apply_qtest_rules(
    x,
    list(
      x_axis = "S1",
      y_axis = "S1",
      colour = c("S1", "0"),
      label_column = c("S1", "0"),
      top_features_to_label = c("X1[1,)", "0")
    ),
    label = "volcano params"
  )
  if (!isTRUE(res)) {
    return(res)
  }

  if (!is.null(x[["top_features_to_label"]]) && is.null(x[["label_column"]])) {
    return("`top_features_to_label` is set but `label_column` is missing.")
  }
  if (!is.null(dt)) {
    res <- checkmate::checkDataFrame(dt)
    if (!isTRUE(res)) {
      return(res)
    }
    needed <- c(
      x[["x_axis"]],
      x[["y_axis"]],
      x[["colour"]],
      x[["label_column"]]
    )
    res <- checkmate::checkSubset(needed, choices = names(dt))
    if (!isTRUE(res)) {
      return(sprintf(
        paste(
          "The following columns are referenced in the params but missing",
          "in dt: %s"
        ),
        paste(setdiff(needed, names(dt)), collapse = ", ")
      ))
    }
  }

  return(TRUE)
}

#' Assert volcano params
#'
#' @inheritParams checkVolcanoParams
#' @param .var.name Name of the checked object to print in assertions.
#' @param add Collection to store assertion messages. See
#' [checkmate::makeAssertCollection()].
#'
#' @returns Invisibly returns the checked object if the assertion is
#' successful.
#'
#' @keywords internal
assertVolcanoParams <- checkmate::makeAssertionFunction(checkVolcanoParams)
