# Generated by devforge. Do not edit.
# Edit the specs under inst/params/ and run devforge::forge_params().

# parameter wrappers -----------------------------------------------------------

#' Wrapper function for standard plot parameters
#'
#' @param width Numeric. Width of the plot. Defaults to `5.0`.
#' @param height Numeric. Height of the plot. Defaults to `5.0`.
#' @param file_type String. Plot type to save. Might be expanded to other file
#' types. One of `c(".png", ".pdf")`. Defaults to `".png"`.
#' @param unit String. Unit type for `width` and `height`. One of `c("in", "px",
#' "cm")`. Defaults to `"in"`.
#' @param res Integer. Resolution for PNGs. Defaults to `450L`.
#' @param create_dir Boolean. Shall the plot directory be generated recursively.
#' Defaults to `TRUE`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item width - Numeric. Width of the plot. Defaults to `5.0`.
#'  \item height - Numeric. Height of the plot. Defaults to `5.0`.
#'  \item file_type - String. Plot type to save. Might be expanded to other file
#'  types. One of `c(".png", ".pdf")`. Defaults to `".png"`.
#'  \item unit - String. Unit type for `width` and `height`. One of `c("in",
#'  "px", "cm")`. Defaults to `"in"`.
#'  \item res - Integer. Resolution for PNGs. Defaults to `450L`.
#'  \item create_dir - Boolean. Shall the plot directory be generated
#'  recursively. Defaults to `TRUE`.
#' }
#'
#' @export
params_plots <- function(
  width = 5.0,
  height = 5.0,
  file_type = c(".png", ".pdf"),
  unit = c("in", "px", "cm"),
  res = 450L,
  create_dir = TRUE
) {
  file_type <- match.arg(file_type)
  unit <- match.arg(unit)

  # Checks
  checkmate::qassert(width, "N1")
  checkmate::qassert(height, "N1")
  checkmate::assertChoice(file_type, c(".png", ".pdf"))
  checkmate::assertChoice(unit, c("in", "px", "cm"))
  checkmate::qassert(res, "I1")
  checkmate::qassert(create_dir, "B1")

  # Return
  list(
    width = width,
    height = height,
    file_type = file_type,
    unit = unit,
    res = res,
    create_dir = create_dir
  )
}

#' Wrapper function for volcano plot parameters
#'
#' @param x_axis String. Column holding the effect size (e.g. `"log2FC"`).
#' Defaults to `"log2FC"`.
#' @param y_axis String. Column holding the raw significance values (e.g.
#' `"FDR"`, `"fdr"`, `"q_value"`). The function applies `-log10()` internally.
#' Defaults to `"FDR"`.
#' @param colour String or `NULL`. Column to colour points by (continuous
#' gradient). If `NULL`, points are coloured by `x_axis`. Defaults to `NULL`.
#' @param label_column String or `NULL`. Column holding feature labels. Required
#' if `top_features_to_label` is set. Defaults to `NULL`.
#' @param top_features_to_label Integer or `NULL`. Number of features to label,
#' ranked by `y_axis` ascending (most significant first). Defaults to `NULL`.
#'
#' @returns A named list with the following elements:
#' \itemize{
#'  \item x_axis - String. Column holding the effect size (e.g. `"log2FC"`).
#'  Defaults to `"log2FC"`.
#'  \item y_axis - String. Column holding the raw significance values (e.g.
#'  `"FDR"`, `"fdr"`, `"q_value"`). The function applies `-log10()` internally.
#'  Defaults to `"FDR"`.
#'  \item colour - String or `NULL`. Column to colour points by (continuous
#'  gradient). If `NULL`, points are coloured by `x_axis`. Defaults to `NULL`.
#'  \item label_column - String or `NULL`. Column holding feature labels.
#'  Required if `top_features_to_label` is set. Defaults to `NULL`.
#'  \item top_features_to_label - Integer or `NULL`. Number of features to
#'  label, ranked by `y_axis` ascending (most significant first). Defaults to
#'  `NULL`.
#' }
#'
#' @export
params_volcano <- function(
  x_axis = "log2FC",
  y_axis = "FDR",
  colour = NULL,
  label_column = NULL,
  top_features_to_label = NULL
) {
  # Checks
  checkmate::qassert(x_axis, "S1")
  checkmate::qassert(y_axis, "S1")
  checkmate::qassert(colour, c("S1", "0"))
  checkmate::qassert(label_column, c("S1", "0"))
  checkmate::qassert(top_features_to_label, c("X1[1,)", "0"))

  # Return
  list(
    x_axis = x_axis,
    y_axis = y_axis,
    colour = colour,
    label_column = label_column,
    top_features_to_label = top_features_to_label
  )
}
